version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TZ=Asia/Ulaanbaatar
      - PGTZ=Asia/Ulaanbaatar
    networks:
      - network
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres
    restart: always
  server:
    depends_on:
      - db
    build: ./server
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
    networks:
      - network
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"

networks:
  network:

volumes:
  database:
